// Essential File Generated By Firebase Skip it :)

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGmn6kG3tImAv1Y7FIwvVJJtXSXB1TzSo',
    appId: '1:402635277769:web:11d1de8810a308ab945418',
    messagingSenderId: '402635277769',
    projectId: 'map-tile-bb653',
    authDomain: 'map-tile-bb653.firebaseapp.com',
    storageBucket: 'map-tile-bb653.appspot.com',
    measurementId: 'G-PZV0D5R203',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBJwCYaFZwhNekU4T5iW3FkndaQnP09II',
    appId: '1:402635277769:android:061c969bbbfdc086945418',
    messagingSenderId: '402635277769',
    projectId: 'map-tile-bb653',
    storageBucket: 'map-tile-bb653.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2xAlOfzWOPJjr53livJZplluvbkB4ceg',
    appId: '1:402635277769:ios:ca7a84153c711a33945418',
    messagingSenderId: '402635277769',
    projectId: 'map-tile-bb653',
    storageBucket: 'map-tile-bb653.appspot.com',
    androidClientId: '402635277769-1ek01u39of0es1gi1msvbhjcd1vmqkgm.apps.googleusercontent.com',
    iosClientId: '402635277769-0fu33g5hrcoiibfmk342c9jk05p0dm42.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapTile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2xAlOfzWOPJjr53livJZplluvbkB4ceg',
    appId: '1:402635277769:ios:ca7a84153c711a33945418',
    messagingSenderId: '402635277769',
    projectId: 'map-tile-bb653',
    storageBucket: 'map-tile-bb653.appspot.com',
    androidClientId: '402635277769-1ek01u39of0es1gi1msvbhjcd1vmqkgm.apps.googleusercontent.com',
    iosClientId: '402635277769-0fu33g5hrcoiibfmk342c9jk05p0dm42.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapTile',
  );
}
